/**
 * @file mmu.h
 * @brief Memory Management Unit interface for hardware address translation.
 */

#ifndef VMM_MMU_H
#define VMM_MMU_H

#include "vmm/types.h"
#include "vmm/ram.h"
#include "vmm/page_table.h"
#include "vmm/tlb.h"

/** @brief Translation Result Status. */
typedef enum
{
    MMU_SUCCESS = 0,
    MMU_PAGE_FAULT,
    MMU_PROTECTION_FAULT,
    MMU_INVALID_ADDRESS
} mmu_status_t;

/** @brief Memory Management Unit controller state. */
typedef struct
{
    ram_t *ram;                /**< Pointer to physical RAM. */
    page_table_t *page_table;  /**< Pointer to current active Page Table. */
    tlb_t *tlb;                /**< Pointer to TLB Cache. */
    uint32_t page_offset_bits; /**< Number of bits used for offset (e.g. 12 for 4KB). */

    // Performance Statistics
    uint64_t total_translations;
    uint64_t page_faults;
} mmu_t;

/**
 * @brief Initializes MMU hardware component.
 * @param mmu Pointer to allocated mmu_t structure.
 * @param ram Pointer to initialized RAM instance.
 * @param pt Pointer to initialized Page Table.
 * @param page_offset_bits Offset width in bits (from vmm_config_t).
 */
void mmu_init(mmu_t *mmu, ram_t *ram, page_table_t *pt, tlb_t *tlb, uint32_t page_offset_bits);

/**
 * @brief Translates Virtual Address to Physical Address using Page Table.
 * @param mmu Pointer to mmu_t instance.
 * @param vaddr Virtual address generated by CPU.
 * @param req_flag Required permission flag (READ, WRITE, EXECUTE).
 * @param out_paddr Output pointer to store translated physical address.
 * @return MMU_SUCCESS, MMU_PAGE_FAULT, or MMU_PROTECTION_FAULT.
 */
mmu_status_t mmu_translate(mmu_t *mmu, vaddr_t vaddr, page_flags_t req_flag, paddr_t *out_paddr);

// Bitwise helper extraction functions
vpn_t mmu_extract_vpn(vaddr_t vaddr, uint32_t page_offset_bits);
offset_t mmu_extract_offset(vaddr_t vaddr, uint32_t page_offset_bits);

#endif // VMM_MMU_H