/**
 * @file types.h
 * @brief Core primitive types and definitions for the Virtual Memory Manager Simulator.
 */

#ifndef VMM_TYPES_H
#define VMM_TYPES_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <sys/types.h>

/** @brief Virtual Address representation (64-bit unsigned integer). */
typedef uint64_t vaddr_t;

/** @brief Physical Address representation (64-bit unsigned integer). */
typedef uint64_t paddr_t;

/** @brief Virtual Page Number representation. */
typedef uint32_t vpn_t;

/** @brief Physical Frame Number representation. */
typedef uint32_t pfn_t;

/** @brief Memory offset within a page or frame. */
typedef uint32_t offset_t;

/** @brief Memory Access Operation Types. */
typedef enum
{
    MEM_OP_READ = 0,
    MEM_OP_WRITE,
    MEM_OP_EXECUTE
} mem_op_type_t;

/** @brief Page Table Entry Flags bitmask enumeration. */
typedef enum
{
    PAGE_FLAG_NONE = 0,
    PAGE_FLAG_PRESENT = (1 << 0),    /**< Page is resident in physical memory. */
    PAGE_FLAG_READABLE = (1 << 1),   /**< Page allows read operations. */
    PAGE_FLAG_WRITABLE = (1 << 2),   /**< Page allows write operations. */
    PAGE_FLAG_EXECUTABLE = (1 << 3), /**< Page allows execution. */
    PAGE_FLAG_DIRTY = (1 << 4),      /**< Page has been modified. */
    PAGE_FLAG_ACCESSED = (1 << 5),   /**< Page has been accessed recently. */
    PAGE_FLAG_SWAPPED = (1 << 6)     /**< Page resides in swap space. */
} page_flags_t;

/** @brief Representing a Memory Access Request generated by CPU. */
typedef struct
{
    vaddr_t virtual_address;
    mem_op_type_t op_type;
    uint32_t process_id;
    uint64_t timestamp;
} mem_access_req_t;

#endif // VMM_TYPES_H